### ISSUE TITLE
Unhandled CimSubModeGarage panic

### ISSUE THREAD

**Issue by theangryangel** [theangryangel/insim.rs#189]
```
thread 'main' panicked at insim/src/insim/cim.rs:137:17:
internal error: entered unreachable code: Unhandled CimSubModeGarage. Perhaps a programming error or protocol update?
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: <insim::insim::cim::CimSubModeGarage as core::convert::From<u8>>::from
             at /home/karl/Code/insim.rs/insim/src/insim/cim.rs:137:17
   3: <T as core::convert::Into<U>>::into
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/convert/mod.rs:759:9
   4: <insim::insim::cim::CimMode as binrw::binread::BinRead>::read_options
             at /home/karl/Code/insim.rs/insim/src/insim/cim.rs:189:31
   5: <insim::insim::cim::Cim as binrw::binread::BinRead>::read_options::{{closure}}
             at /home/karl/Code/insim.rs/insim/src/insim/cim.rs:237:1
   6: <insim::insim::cim::Cim as binrw::binread::BinRead>::read_options
             at /home/karl/Code/insim.rs/insim/src/insim/cim.rs:237:1
   7: <insim::packet::Packet as binrw::binread::BinRead>::read_options::{{closure}}::{{closure}}
             at /home/karl/Code/insim.rs/insim/src/packet.rs:7:1
   8: <insim::packet::Packet as binrw::binread::BinRead>::read_options::{{closure}}
             at /home/karl/Code/insim.rs/insim/src/packet.rs:7:1
   9: <insim::packet::Packet as binrw::binread::BinRead>::read_options
             at /home/karl/Code/insim.rs/insim/src/packet.rs:7:1
  10: binrw::binread::BinRead::read_args
             at /home/karl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/binrw-0.14.0/src/binread/mod.rs:116:9
  11: binrw::binread::BinRead::read
             at /home/karl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/binrw-0.14.0/src/binread/mod.rs:62:9
  12: insim::net::codec::Codec::decode
             at /home/karl/Code/insim.rs/insim/src/net/codec.rs:73:22
  13: insim::net::tokio_impl::framed::FramedInner<N>::read::{{closure}}
             at /home/karl/Code/insim.rs/insim/src/net/tokio_impl/framed.rs:71:39
  14: insim::net::tokio_impl::framed::Framed::read::{{closure}}::{{closure}}
             at /home/karl/Code/insim.rs/insim/src/net/tokio_impl/framed.rs:154:46
  15: insim::net::tokio_impl::framed::Framed::read::{{closure}}
             at /home/karl/Code/insim.rs/insim/src/net/tokio_impl/framed.rs:148:5
  16: strobe::main::{{closure}}::{{closure}}
             at /home/karl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/macros/select.rs:524:49
  17: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /home/karl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/future/poll_fn.rs:58:9
  18: strobe::main::{{closure}}
             at ./src/main.rs:96:9
  19: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/karl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/park.rs:283:63
  20: tokio::runtime::coop::with_budget
             at /home/karl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/coop.rs:107:5
  21: tokio::runtime::coop::budget
             at /home/karl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/coop.rs:73:5
  22: tokio::runtime::park::CachedParkThread::block_on
             at /home/karl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/park.rs:283:31
  23: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/karl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/context.rs:315:13
  24: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/karl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/scheduler/multi_thread/mod.rs:66:9
  25: tokio::runtime::runtime::Runtime::block_on
             at /home/karl/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.1/src/runtime/runtime.rs:304:45
  26: strobe::main
             at ./src/main.rs:95:5
  27: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by theangryangel** [comment]
Cant seem to reproduce this by flicking through the . I'm not sure when it happened exactly, but it was during tonight's Piran DD.

It implies that sometimes LFS is sending a GRG_NUM.. or there's something else off in the `Cim` packet handling :/

**Comment by theangryangel** [comment]
Have been unable to reproduce this with tonights Piran DD event :/

**Comment by Cykyrios** [comment]
Hey, I'm just reading through the issues to see what you're doing/planning with this repo, and noticed this one. I was wondering if this was related to the mod rating tab in the garage? I had this happen to me, the rating tab sends 255 as a submode, so for GodotInSim I added it in the submode enum (it's not documented in InSim.txt).

**Comment by theangryangel** [comment]
Oooh, I'll have a look Cykyrios <3 Thank you!

Still working on this, but progress has massively slowed down with my daughter going to bed later and later 😅
